---

homebrew__div: "### Homebrew"
homebrew__path: 'PATH={{ homebrew_install_path }}/sbin:{{ homebrew_install_path }}/bin:$PATH'
homebrew__path_prefix: 'PATH='
homebrew__no_analytics: 'export HOMEBREW_NO_ANALYTICS=1'
homebrew__no_insecure_redirect: 'export HOMEBREW_NO_INSECURE_REDIRECT=1'
homebrew__require_sha: 'export HOMEBREW_CASK_OPTS=--require-sha'

homebrew_prefix: "{{ home }}/.homebrew"
homebrew_install_path: "{{ homebrew_prefix }}"
homebrew_brew_bin_path: "{{ homebrew_prefix }}/bin"

homebrew_installed_packages: []

homebrew_uninstalled_packages: []

homebrew_upgrade_all_packages: yes

homebrew_taps:
    - buo/cask-upgrade
    - caskroom/cask
    - caskroom/versions
    - homebrew/bundle
    - homebrew/core
    - homebrew/dupes

homebrew_cask_apps: []

homebrew_cask_appdir: /Applications

homebrew_use_brewfile: false
homebrew_brewfile_dir: '~'
